name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install
          cd client && npm install
          cd ../server && npm install

      - name: Setup MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: '7.0'

      - name: Create env file
        run: |
          echo "MONGODB_URI=mongodb://127.0.0.1:27017/tech-quiz" > server/.env
          echo "PORT=3003" >> server/.env
          echo "NODE_ENV=development" >> server/.env

      - name: Build client
        run: |
          cd client
          npm run build || (echo "Build failed, checking TypeScript configuration" && cat tsconfig.json && cat tsconfig.node.json && exit 1)

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm run start:dev
          wait-on: 'http://localhost:3003'
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MONGODB_URI: mongodb://127.0.0.1:27017/tech-quiz
          PORT: 3003
          NODE_ENV: development 